#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin:
  resource: ../src/Controller/Admin
  prefix: /admin
  name_prefix: admin_
  type: annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"